/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e0e3e5',
        'on-primary-container': '#fefcff',
        'tertiary-fixed': '#efdbff',
        'secondary-fixed-dim': '#47e266',
        'primary-container': '#0070eb',
        'background': '#f7f9fb',
        'surface': '#f7f9fb',
        'outline': '#717786',
        'on-error-container': '#93000a',
        'secondary-fixed': '#6cff82',
        'secondary': '#006e26',
        'inverse-surface': '#2d3133',
        'on-primary': '#ffffff',
        'surface-variant': '#e0e3e5',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'on-primary-fixed-variant': '#004493',
        'error': '#ba1a1a',
        'inverse-on-surface': '#eff1f3',
        'tertiary-container': '#8766aa',
        'secondary-container': '#64fd7d',
        'primary-fixed-dim': '#adc6ff',
        'on-secondary-fixed': '#002106',
        'surface-container-high': '#e6e8ea',
        'on-background': '#191c1e',
        'on-surface': '#191c1e',
        'outline-variant': '#c1c6d7',
        'on-tertiary': '#ffffff',
        'surface-dim': '#d8dadc',
        'tertiary-fixed-dim': '#dbb8ff',
        'primary': '#0058bc',
        'primary-fixed': '#d8e2ff',
        'on-surface-variant': '#414755',
        'surface-container-low': '#f2f4f6',
        'inverse-primary': '#adc6ff',
        'error-container': '#ffdad6',
        'surface-bright': '#f7f9fb',
        'on-secondary-container': '#007328',
        'on-tertiary-fixed-variant': '#573878',
        'surface-container': '#eceef0',
        'on-secondary': '#ffffff',
        'on-primary-fixed': '#001a41',
        'on-tertiary-fixed': '#29074a',
        'tertiary': '#6d4e8f',
        'surface-tint': '#005bc1',
        'on-secondary-fixed-variant': '#00531a',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
